apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: bavoandriessen/apigateway:latest
        env:
        - name: CONTAINER_MANAGEMENT_HOST
          value: "container-management-service.default.svc.cluster.local"
        - name: ADMINISTRATION_HOST
          value: "administration-service.default.svc.cluster.local"
        - name: KAPITEINSDIENST_HOST
          value: "kapiteinsdienst-service.default.svc.cluster.local"
        - name: BERTH_HOST
          value: "berth-service.default.svc.cluster.local"
        - name: MAINTENANCE_HOST
          value: "maintenance-service.default.svc.cluster.local"
        - name: TOWINGPILOTAGE_HOST
          value: "towingpilotage-service.default.svc.cluster.local"
        - name: VTC_HOST
          value: "vtc-service.default.svc.cluster.local"
        ports:
        - containerPort: 8080
