@startuml aanmelding van een binnenvaart

actor Scheepsagent
Scheepsagent ->> "API Gateway": registerVessel
"API Gateway" ->> Kapiteinsdienst: registerVessel
activate Kapiteinsdienst

Kapiteinsdienst ->> "Ligplaats en dokbeheer": reserveBerth
activate "Ligplaats en dokbeheer"
Kapiteinsdienst ->> "loods- en sleepbootdienst": reserveTowingPilotage
activate "loods- en sleepbootdienst"
Kapiteinsdienst ->> onderhoudsdienst: reserveService
activate "onderhoudsdienst"
Kapiteinsdienst ->> Administratie: createOffer
activate "Administratie"

Kapiteinsdienst <<-- "Ligplaats en dokbeheer": berthReserved
deactivate "Ligplaats en dokbeheer"
Kapiteinsdienst <<-- "loods- en sleepbootdienst": towingPilotageReserved
deactivate "loods- en sleepbootdienst"
Kapiteinsdienst <<-- onderhoudsdienst: serviceReserved
deactivate "onderhoudsdienst"
Kapiteinsdienst <<-- Administratie: offerCreated
deactivate "Administratie"



alt Reservations and offer creation succeeded
    Scheepsagent ->> "API Gateway": getOffer
    "API Gateway" ->> Kapiteinsdienst: getOffer

    Kapiteinsdienst -->> "API Gateway": return offer
    "API Gateway" -->> Scheepsagent: return offer

    

    alt Scheepsagent accepts offer
        Scheepsagent ->> "API Gateway": offerConfirmation(isConfirmed = true)
        "API Gateway" ->> Kapiteinsdienst: offerConfirmation(isConfirmed = true)
        
    else Scheepsagent rejects offer
        Scheepsagent ->> "API Gateway": offerConfirmation(isConfirmed = false)
        "API Gateway" ->> Kapiteinsdienst: offerConfirmation(isConfirmed = false)
        Kapiteinsdienst ->> "Ligplaats en dokbeheer": undoReservation
        activate "Ligplaats en dokbeheer"
        deactivate "Ligplaats en dokbeheer"
        Kapiteinsdienst ->> "loods- en sleepbootdienst": undoReservation
        activate "loods- en sleepbootdienst"
        deactivate "loods- en sleepbootdienst"
        Kapiteinsdienst ->> "onderhoudsdienst": undoReservation
        activate "onderhoudsdienst"
        deactivate "onderhoudsdienst"
        Kapiteinsdienst ->> "Administratie": deleteOffer
        activate "Administratie"
        deactivate "Administratie"
    end

else failure during reservation or offer creation
    
    
    Kapiteinsdienst ->> "Ligplaats en dokbeheer": undoReservation
    activate "Ligplaats en dokbeheer"
    deactivate "Ligplaats en dokbeheer"
    Kapiteinsdienst ->> "loods- en sleepbootdienst": undoReservation
    activate "loods- en sleepbootdienst"
    deactivate "loods- en sleepbootdienst"
    Kapiteinsdienst ->> "onderhoudsdienst": undoReservation
    activate "onderhoudsdienst"
    deactivate "onderhoudsdienst"
    Kapiteinsdienst ->> "Administratie": deleteOffer
    activate "Administratie"
    deactivate "Administratie"
end


@enduml