@startuml aanmelding van een binnenvaart

actor Scheepsagent
Scheepsagent ->> "API Gateway": createOffer
"API Gateway" ->> Kapiteinsdienst: createOffer
activate Kapiteinsdienst

Kapiteinsdienst ->> "Ligplaats en dokbeheer": reserveBerth
activate "Ligplaats en dokbeheer"
Kapiteinsdienst ->> "loods- en sleepbootdienst": reserveTowing/Pilotage
activate "loods- en sleepbootdienst"
Kapiteinsdienst ->> onderhoudsdienst: reserveService
activate "onderhoudsdienst"
Kapiteinsdienst ->> Administratie: createOffer
activate "Administratie"

Kapiteinsdienst <<-- "Ligplaats en dokbeheer": berthReserved
deactivate "Ligplaats en dokbeheer"
Kapiteinsdienst <<-- "loods- en sleepbootdienst": towing/PilotageReserved
deactivate "loods- en sleepbootdienst"
Kapiteinsdienst <<-- onderhoudsdienst: serviceReserved
deactivate "onderhoudsdienst"
Kapiteinsdienst <<-- Administratie: offerCreated
deactivate "Administratie"



alt Reservations and offer creation succeeded
    Kapiteinsdienst -->> "API Gateway": offerProposal (success)
    "API Gateway" -->> Scheepsagent: offerProposal (success)

    

    alt Scheepsagent accepts offer
        Scheepsagent ->> "API Gateway": acceptOffer
        "API Gateway" ->> Kapiteinsdienst: acceptOffer
        
    else Scheepsagent rejects offer
        Scheepsagent ->> "API Gateway": refuseOffer
        "API Gateway" ->> Kapiteinsdienst: refuseOffer
        Kapiteinsdienst ->> "Ligplaats en dokbeheer": undoReservation
        activate "Ligplaats en dokbeheer"
        deactivate "Ligplaats en dokbeheer"
        Kapiteinsdienst ->> "loods- en sleepbootdienst": undoReservation
        activate "loods- en sleepbootdienst"
        deactivate "loods- en sleepbootdienst"
        Kapiteinsdienst ->> "onderhoudsdienst": undoReservation
        activate "onderhoudsdienst"
        deactivate "onderhoudsdienst"
    end

else failure during reservation or offer creation
    Kapiteinsdienst -->> "API Gateway": offerProposal (failure)
    "API Gateway" -->> Scheepsagent: offerProposal (failure)
    
    Kapiteinsdienst ->> "Administratie": deleteOffer
    activate "Administratie"
    deactivate "Administratie"
    Kapiteinsdienst ->> "Ligplaats en dokbeheer": undoReservation
    activate "Ligplaats en dokbeheer"
    deactivate "Ligplaats en dokbeheer"
    Kapiteinsdienst ->> "loods- en sleepbootdienst": undoReservation
    activate "loods- en sleepbootdienst"
    deactivate "loods- en sleepbootdienst"
    Kapiteinsdienst ->> "onderhoudsdienst": undoReservation
    activate "onderhoudsdienst"
    deactivate "onderhoudsdienst"
end


@enduml