apiVersion: v1
kind: Service
metadata:
  name: container-management-service
spec:
  selector:
    app: container-management
  ports:
  - port: 8080
    targetPort: 8080
  externalIPs:
  - 192.168.0.209
