version: "3.9" 
services:
# ------------Support services-------------
  container-db:
    image: postgres:latest
    container_name: container-db
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=containers
     - POSTGRES_HOST_AUTH_METHOD="password"
    ports:
     - "5432:5432"
    volumes:
     - ./sql/containerdb.sql:/docker-entrypoint-initdb.d/create_tables.sql 
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
     - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka
    depends_on: 
      - zookeeper
    environment: 
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports: 
     - "9092:9092"
    links:
     - zookeeper
# ------------Core services----------------
  container-management:
    container_name: container-management
    build: ../services/containermanagement
    environment: 
    - DOCKERCOMPOSEDATASOURCEURL="--spring.datasource.url=jdbc:postgresql://container-db:5432/containers"
    ports:
     - "1234:8080"
    depends_on:
     - container-db
     - kafka
    links:
     - kafka
     - container-db
