apiVersion: apps/v1
kind: Deployment
metadata:
  name: administration-db-deployment
  labels:
    app: administration-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: administration-db
  template:
    metadata:
      labels:
        app: administration-db
    spec:
      containers:
      - name: administration-db
        image: postgres:latest
        env: 
         - name: POSTGRES_USER
           value: postgres
         - name: POSTGRES_PASSWORD 
           value: pwd
         - name: POSTGRES_DB
           value: administration
         - name: POSTGRES_HOST_AUTH_METHOD
           value: password
        ports:
        - containerPort: 5432
          name: postgres